export const GET_LEHENGA_DATA_R = "GET_LEHENGA_DATA_R";
export const GET_LEHENGA_DATA_S = "GET_LEHENGA_DATA_S";
export const GET_LEHENGA_DATA_F = "GET_LEHENGA_DATA_F";
export const GET_SUITS_DATA_S = "GET_SUITS_DATA_S";
export const GET_GOWN_DATA_S = "GET_GOWN_DATA_S";

export const GET_HOMEDATA_S = "GET_DATA_S";